version: "3.9"
services:
  app:
    container_name: ${NAME_CONTAINER}
    image: backexample:1.0
    ports:
      - 3000:3000
    networks:
      - red_ayra
      
networks:
  red_ayra:
    external: true